micronaut:
  application:
    name: micronautguide
  http:
    client:
      read-timeout: 120s
#tag::db[]
db:
  name: 'Pega'
  collection: 'Employee'
#end::db[]
mongodb:
  uri: mongodb://localhost:27017/
