micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  application:
    name: EmployeePortal
  http:
    client:
      read-timeout: 120s
#tag::db[]
db:
  name: 'Pega'
  collection: 'Employee'
#end::db[]
mongodb:
  uri: mongodb://localhost:27017/
