micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  application:
    name: EmployeePortal
  http:
    port: 8080
    client:
      read-timeout: 120s
  secure:
    port: 8443
    enabled: true
  ssl:
    enabled: false
    certificate:
      path: "keystore.p12"
      password: "123456"
#tag::db[]
db:
  name: 'Pega'
  collection: 'Employee'
#end::db[]
mongodb:
  uri: mongodb://localhost:27017/
